* 秋天
** 高中时的秋
** 大学时的秋
** 母亲生病时的秋
** 小森林的秋
** 小县城的秋、山里的秋
** 北京的秋
** 郑州的秋天
** 游子的秋
** 收获的球
** 彷徨的秋
** 宁静的秋
** 失恋的秋天
** 初恋的秋天
** 该结婚的秋天
* 哲学
** 归于平凡淡泊
** 平静的回忆
** 非个性化，抽象
** 赞美生命
* 节奏
** 冷静
** 理性
** 淡泊
** 坚定
* 韵律
** 自由韵
** 反复
* 线索
** 这是我一生中最好的一个秋天。不，或许是我最愿意相信的的一个美好的秋天。黄叶铺满了泛黄的草地，我坐在一颗椿树下读诗。秋风又一次温柔的走来，我打算好好地陪她叙叙旧。
** 12年前，高一，我喜欢在秋天的半夜起来，一个人在院子里散步。高一的四个少年班住在一个小院子里，前边的一幢二层小楼是教室，后边的是宿舍。一个宿舍有两排连成一溜的的上下铺。没有卫生间，刷牙，洗漱都在走廊里。记得当时有同学在宿舍里洗脸或者洗脚，班主任认为这影响宿舍卫生，专门提出批评。于是胖胖的宿舍长当晚就严格强调不能坐在床上洗脚，并给我们表演了如何站着洗脚。一个灵活的大胖子，单脚站在萧瑟的秋风中，另一只脚抬到膝盖上，双手颤抖地揉搓着，神气活现地指挥其他人，然而并没有人向他学习。年少气盛的我痛斥这种行为，号召要民主票选宿舍长，竟有人响应。班主任不仅不同意，反而提出要民主投票决定是否开除我。这些都不重要了。
** 那个院子里有一排杨树，树比二层小楼要高，我总是惊讶，白天那么吵闹拥挤的两幢小楼，一到晚上如此安静。没有了班主任可憎的嘴脸，没有班干部们充满敌意的目光。院子东墙外是黝黑阴森的居民区，西门外是空荡荡的操场，白天迫不及待想去的操场，晚上才发现如此的破败荒凉。院子很小，我一遍遍的在这里绕圈子。听着秋风从远方而来，穿过寂寞的操场，和这一排杨树嬉戏，又消失在残破的居民区。何时我也能像秋风一样。
** 九年前，我终于一个人离开了小镇，来到北京，那是一个明亮的秋天。高大的建筑，宽广的马路，光鲜的人。然而光亮很快暗淡，似乎这里没有我的位置。就像电影《小森林》里的市子.市子一个人住在小森林,一个偏远安静的山村,她一个人包揽了所有的农活，种植了水稻，洋葱，西红柿，菠菜，胡萝卜，芋头，红薯等各种蔬菜，他养着番鸭，小猫，忙时还要去打零工。当她需要购买生活用品时，就骑车到邻村的大超市去，来回需要一天。[<0;55;23M]
** 那时的懵懂是人生最好也是最坏的时光。力不从心时总总感慨当年的青春活力，悔恨辜负了美好时光。然而午夜梦回高中课堂，总是在痛苦压抑中惊醒。那时的秋天，那时的我，依然是一个谜。每每回忆起，总会激励我前行，或许有一个秋天，我能放下渴望收获的心，再去跟遗憾的青春握手言和。
