* 需求
采集，分析，抽象各行业的大数据处理需求，提供一整套完整解决方案。来自各行业的传统企业都可以很方便的使用。
* 产品线
数加提供的服务：对某些行业，某类需求的完整解决方案，例如敏捷BI，路况预测等
吸引第三方开发者：提供基础平台和开放API，吸引开发者为某类需求或某个行业开发解决方案
* 定位
 在大数据图谱中，数加应当属于应用层，它建构在ODPS（阿里开放数据处理服务）之上，而ODPS建构在阿里云基础设施之上。
* ODPS（开放数据处理服务）
** 简介
大数据计算服务ODPS（Open Data Processing Service， 简称ODPS）是由阿里云自主研发，提供针对TB/PB级数据、实时性要求不高的分布式处理能力，应用于数据分析、挖掘、商业智能等领域。阿里巴巴的离线数据业务都运行在ODPS上
** 优势
*** 高效处理海量数据
采用分布式架构处理海量数据，最大集群规模达到5000台，采用比MapReduce框架更加灵活的计算模型
*** 安全
存储多份拷贝，所有计算在沙箱中运行
*** 易用
存储多份拷贝，所有计算在沙箱中运行
*** 授权管理
支持多用户协同分析数据，多种权限管理方式，灵活的数据访问控制策略
** 架构：
计算，存储资源由阿里云提供
预安装一些大数据计算框架
** 计算资源收费方式
 预存款，后付费，按需付费，10cpu,40G内存，1个月，需要1500元。
** 反思
到底是什么计算模型比MapReduce更灵活？
* 敏捷BI：
** 数据来源
*** 不同系统来源的数据整合分析（类似燕峰？）
随着企业业务发展，企业的信息架构中会有不同职责的系统支撑不同企业业务，比如客户管理系统、销售系统、仓储管理系统等等。这些系统往往是由不同供应商开发或提供的，数据分别存储在不同的在线数据库中。企业的数据分析或者商业决策需要整合这些数据进行综合分析，将不同在线系统、不同在线存储的数据整合到同一个平台上进行数据的整合、打通、分析。
*** 不同类型的数据整合分析（类似燕峰？）
    企业在进行互联网化转型之后，往往会开始将用户访问及行为数据，以日志文本的形式记录到服务器，这些属于半结构化数据。而后续数据分析及商业决策，需要将用户行为数据与业务结果数据进行
整合分析。
** 计算引擎
阿里云大数据平台的分布式计算服务提供多样的数据计算引擎，SQL、MR、图计算、MPI等，满足针对不同数据类型、进行不同类型加工的需求。
** 规模
阿里云大数据平台的大数据计算服务能够帮助用户针对TB/PB级数据进行分布式的数据加工，后台强大得计算能力，支持用户做更深度、更复杂的加工。不会因为数据的增长而操
心数据计算能力。使数据工程师专注到数据价值本身的挖掘。
**  架构
    https://help.aliyun.com/document_detail/shujia/platform-brief/solution/agile-BI.html?spm=5176.docshujia/platform-brief/how-to-start.6.82.Z61NEu
* 数据开发：
** 简介
数据开发是数加推出的大数据领域平台级产品，提供一站式大数据开发、管理、分析、挖掘、共享、交换等端到端的解决方案，其利用ODPS在几分钟内可将原始数据转变为业务洞察的海量数据处理能力，而无需关心集群的搭建和运维。
数据开发者可通过数据开发提供的Web IDE编程和调试环境在云端构建数据仓库，充分享受ODPS低成本、高性能的海量数据处理能力；利用数据同步、ODPS SQL、MapReduce、BI报表和机器学习提高数据处理效率，同时支持多人协同开发，交叉测试的场景。
** 架构
*** 组织
组织是大数据平台特有概念，一个公司开通大数据平台服务就创建一个组织，一个组织内创建多个项目空间。 组织之间相互隔离，一个账号只能所属一个组织。元数据按组织隔离，只能查看本组织下的表元数据。
*** 项目空间
项目空间是数据开发中最基本的组织对象，类似于传统数据库的DataBase。数据开发的项目空间，是进行多组织隔离和访问控制的主要边界，也是用户管理表（Table）、资源（Resource）、自定义函数（UDF）、作业（Job）、节点（Node）、工作流（WorkFlow）、权限等的基本单元。
*** 作业（job）
作业是由一个或多个节点（也称任务），及其执行次序关系的工作流（Workflow）组成。作业是一个静态概念，一个已定义的作业可以被反复执行。
*** 工作流（Workflow)
工作流是一个DAG图（有向无环图），其描述了作业中多个节点之间的逻辑（依赖关系）和规则（运行约束）。
*** 节点（Node）
节点属于工作流的子对象，也称之为任务，是数据开发数据处理和分析过程的最基本单元，每个任务对应DAG图中的一个节点，其可以是一个SQL Query、命令和MapReduce程序。
*** 依赖关系（Dependency）
依赖关系是描述两个或多个节点/工作流之间的语义连接关系，其中上游节点/工作流的运行状态可以影响下游节点/工作流的运行状态，反之则不成立。
*** 实例（Instance）
在数据开发中，节点任务在执行时会被实例化，并以ODPS实例的形式存在。实例会经历未运行、等待时间/等待资源、运行中、成功/失败几个状态。
*** 资源（Resource）
资源是数据开发的特有概念，用户可以上传本地自定义的JAR或文件作为资源，在节点运行时调用，如，在数据开发中运行MapReduce程序，需要将MapReduce生成的JAR包上传到平台后，通过节点调用所上传的资源来运行此MapReduce程序。
*** 自定义函数（UDF）
    ODPS提供了Java的编程接口来开发用户自定义函数。在大数据平台数据开发套件中支持Java UDF。
* 机器学习
** 简介
阿里PAI机器学习平台是构建在阿里云ODPS计算平台之上，集数据处理、建模、离线预测、在线预测为一体的机器学习平台。 该平台为算法开发者提供了丰富的MPI、PS、BSP等编程框架和数据存取接口，同时为算法使用者提供了基于Web的IDE+可视化实验搭建控制台。平台目前整合了集团内最先进的算法，为集团内、外不同用户提供算法服务。
** 产品特点
一站式的算法与智能应用的开发、发布与分享的平台
支持处理亿万级大规模数据
无需编码，据简单的拖拽即可完成数据挖掘，数据分析等功能
孕育于阿里“数据-云-计算”生态系统，高效配置计算资源为数据赋能
* 规则引擎
** 简介
规则引擎（Rules Engine）是一款用于解决业务规则频繁变化的在线服务，它能帮助客户将业务规则从应用程序代码中分离出来，通过简单组合预定义的条件因子即可灵活编写业务规则，并根据业务规则做出业务决策。 规则引擎提供一整套的高效、易用的API服务，并配套了简单易用的规则配置界面，能够被业务系统快速集成；对T级别的数据量 通过百万级别的规则进行计算时，可以在毫秒级别返回结果；并放量最高可达10万。 规则引擎可运用于定向营销、物联网智能家居、智能楼宇、调度、预警、控制及派发场景。
* 数据可视化
** 简介
相比于传统图表与数据仪表盘，如今的数据可视化致力于用更生动、友好的形式，即时呈现隐藏在瞬息万变且庞杂数据背后的业务洞察。无论在零售、物流、电力、水利、环保、还是交通领域，通过交互式实时数据可视化视屏墙来帮助业务人员发现、诊断业务问题，越来越成为大数据解决方案中不可或缺的一环。
** 行业痛点
对于数据可视化的设计无从下手，团队内的设计师对于复杂数据的展现经验不足
对于数据可视化的实现比较困难，设计出来的很多图表与特效开发耗时耗力
对于非传统报表数据类型（如时空数据、关系数据）的分析展现，缺乏相关的组件/工具支持
对于在大屏幕上的展示，总会遇到分辨率适配的种种问题
对于大数据的分析展示，现有工具无法很好支撑
** 阿里DataV特性
 多种场景模板，解决您的设计难题
 多种图表组件，支撑多种数据类型的分析展示
 多种数据源接入，充分发挥阿里云大数据计算的能力
 图形化的搭建工具，无需专业编程人员也可快速实现
 多分辨率适配与发布方式，满足您不同场合下的使用
