* 大数据科研实验云
我校大数据研究团队快速成长，越来越多的导师，学生参与到大数据研究的各个领域，包括大数据采集，大数据存储，数据模型，图处理框架，刘处理框架，数据可视化，大数据挖掘算法，大数据应用等多个领域。为了支撑这些团队的科研工作，我们团队开发了大数据科研实验云系统，提供了云化的大数据编程，测试，部署，运行环境，使各研究团队能够更专注于一些前瞻性的研究工作，而无需在软硬件环境安装配置，开发测试运行环境搭建方面浪费时间和资源。

* 团队历史
系统软件研究室目前有教师 9 人，博士生 17人，硕士生 24 人，本科实习生 20 余人。研究室主任为黄罡教授。研究室教师还包括梅宏院士、陈向群教授、百人计划研究员熊英飞、孙艳春副教授、郭耀副教授、曹东刚副教授、刘譞哲副教授和助理研究员张颖。
系统软件研究室围绕操作系统和中间件开展研究，过去主要的研究方向包括：
1.操作系统与中间件。研究新型网络化操作系统与中间件的基本结构、运行机理、以及开发和运行支撑技术。
2.移动与嵌入式软件系统。研究面向新型智能移动终端和新型物联网嵌入式设备上的操作系统、中间件与应用软件的开发、优化和应用技术
3.程序设计模型及语言。面向互联网、多核、服务计算、普适计算、信息物理融合系统等新型计算与应用模式，研究并行编程、数据同步编程等新型程序设计模型，以及对应的程序设计语言的定义、分析和验证方法、编程辅助技术和工具等内容。
4.互联网软件运行与优化技术。面向云计算、移动互联网、物联网和大数据等以互联网为核心的新型计算和应用模式，研究互联网软件运行机理与体系结构，以及互操作、性能、可靠、伸缩性、安全、隐私、能效等关键运行性质的监测、保障与优化技术等内容。
* 突出成果
自 2000 年以来，研究室开始以互联网计算机为主线，研究如何利用 Internet 为核心的多网融合，实现高性价比、高效能、高可信的信息化技术；在应用方面，研究如何利用以 Internet 为核心的信息化技术，实现成本控制、资产增值、业务创新。
从 2010 年以来，以互联网计算及其延伸为主线，研究以网构软件为范型的新一代网络操作系统，包括软件定义的云操作系统、云端融合操作系统、大数据操作系统和协作机器人操作系统等.

* 学术影响力

* 成功的典型案例
** pkuas
开源JEE应用服务器 PKUAS 2010 是国家科技重大专项项目“国产中间件参考实现及平台”的重要组成部分, 由 北京大学 信息科学技术学院 软件工程研究所研发. PKUAS2010在功能上兼容Java EE 5(Java Platform, Enterprise Edition 5)规范和Enterprise JavaBean 3.0规范中的核心内容， 全面支持基于J2EE/EJB体系结构的应用。PKUAS2010在实现上采用基于OSGI微内核的开放架构, 易于裁剪、配置、管理，对资源要求低而运行效率高，具有良好的互操作能力和出色的定制与扩展能力，性价比突出。
PKUAS2010将支持 实时应用、 高可信应用、大规模协作应用等网络新型应用模式, 并为应用提供在线演化服务等, 将成为 网构(Internetware)应用的实验平台.
** 燕云
燕云系统使用业界先进的云计算技术，将虚拟化数据中心资源转变为弹性云计算环境，帮助企业快速构建公共、私有和混合基础架构云服务（IaaS），为用户提供自服务门户，实现按需获取计算、网络和存储资源，管理大量的异构虚拟化资源。同时，燕云平台提供开放的API接口，为用户提供安全、可扩展的基础架构云。
** docklet
Docklet系统是一个支持多用户的大数据科研实验云环境。它利用容器技术将物理集群资源虚拟化，并弹性地分配给多用户，使每个用户都能获得一个大数据科研实验工作区，可以简单易用的进行大数据编程，调试，运行。Docklet已在软工所内部运行半年多。该系统将大数据处理所需的各种软硬件基础设施、平台、工具以服务的方式提供给用户使用，不但因资源共享大幅节约成本，而且可极大降低大数据处理的门槛，帮助非计算机专业的师生顺利开展大数据分析活动。
=SUM(IF(H2="",3,H2),IF(I2="",3,I2),IF(J2="",3,J2),IF(K2="",3,K2),IF(L2="",3,L2),IF(M2="",3,M2),IF(N2="",3,N2),)/21*30
