* introduction
** isolation is central to increased reliability and improved performance of modern computer systems
** one aspect of current system design has remained devoid of isolation: the physical on-disk structures of file systems.
*** for example, Linux Ext3 includes all current update activity into a single global transaction, leading to painful and well-documented performance problems.
** the surprising entanglement found in these systems arises from a central truth: logically-independent file system entities are not physically independent. the result is poor reliability, poor performance, or both.
** our remedy to this problem is realized in a new file system we call IceFS. IceFS provides users with a new basic abstraction in which to co-locate logically similar information; we call these containers cubes.
** To realize disentanglement, IceFS is built upon three core principles.
*** First, there should be no shared physical resources across cubes
*** Second, there should be no access dependencies.
*** Third, there should be no bundled transactions.
