* Introduction of DCOS
** why we need a data center operation system?
*** Managing a datacenter was very hard, recently the popular of microservices and big data frameworks make it worse. we need a tool to manage the whole resources of a data center, including computing, storages, network infrastructures, and to provide a unified interface to control, monit the whole datacenter. The main challenges are to improve resource utilization and to make it user-friendly.
** what types of workloads can I run on DCOS?
The DCOS can run nearly any type of workload. Among the dozens of services it supports are databases such as Cassandra and MemSQL; big data systems such as Hadoop and Spark; and orchestration services like Marathon and Kubernetes for hosting long-running and cloud-native applications.
** What are some popular use cases for Mesos and the DCOS?
Although the DCOS supports nearly every type of workload, it is especially popular for supporting Platform-as-a-Service (PaaS) offerings, big data analytics (e.g., Hadoop, Spark and Kafka), as well as stateful services such as HDFS, Cassandra and MemSQL. Coming soon will be support for even more diverse services, including traditional SQL databases such as MySQL.
** what are the main advantages of DCOS over othere solutions, such as CoreOS+Kubernetes or Openstack?
*** run everything on the same shared cluster
Gone are the days of 12-15% datacenter and cloud utilization. The DCOS multiplexes all of your workloads across the entire cluster, automatically "bin-packing" applications onto shared machines for maximum utilization.
*** scaling the elastic datacenter
Your infrastructure needs aren't static, and neither is the DCOS. We make it easy to add new resources to the pool as your business grows and new services come online.
*** simple, powerful interfaces
It has never been easier to deploy distributed services or view the health of tens of thousands of servers.
** how is the mesosphere DCOS different from apache mesos?
The DCOS is a robust and commercially supported software product that is built on top of the open source Mesos. Major improvements in the DCOS include its command line and web interfaces, its simple packaging and installation, and its growing ecosystem of technology partners.
** how is DCOS cluster different from a private cloud, or from virtualization?
The DCOS is the next-generation private cloud. It’s different from software involving virtual machines because the DCOS organizes servers of any kind — physical, virtual or cloud — into a single pool of shared resources. Its Mesos core dynamically provisions the necessary compute, memory and storage resources, rather than preconfigured machine images.
** how is DCOS different from other container technologies, such as Kubernetes and Dcoker?
The DCOS supports both Kubernetes and Docker. Because the DCOS manages infrastructure at the server level and runs directly atop Linux servers, it is able to launch Docker containers at scale. Mesosphere and Google have collaborated to bring Kubernetes to DCOS, where Kubernetes talks directly to the DCOS API and runs like any other DCOS service.
* Introduction of CoreOS+KubernetesOSS (Operational Support System)
** why we should use containers?
*** Application-centric management:
Raises the level of abstraction from running an OS on virtual hardware to running an application on an OS using logical resources. This provides the simplicity of PaaS with the flexibility of IaaS and enables you to run much more than just 12-factor apps.
*** Dev and Ops separation of concerns:
Provides separatation of build and deployment; therefore, decoupling applications from infrastructure.
*** Agile application creation and deployment:
Increased ease and efficiency of container image creation compared to VM image use.
*** Continuous development, integration, and deployment:
Provides for reliable and frequent container image build and deployment with quick and easy rollbacks (due to image immutability).
*** Loosely coupled, distributed, elastic, liberated micro-services:
Applications are broken into smaller, independent pieces and can be deployed and managed dynamically -- not a fat monolithic stack running on one big single-purpose machine.
*** Environmental consistency across development, testing, and production:
Runs the same on a laptop as it does in the cloud.
*** Cloud and OS distribution portability:
Runs on Ubuntu, RHEL, on-prem, or Google Container Engine, which makes sense for all environments: build, test, and production.
*** Resource isolation:
Predictable application performance.
*** Resource utilization:
High efficiency and density.

** what is kubernetes
Kubernetes is an open-source platform for automating deployment, scaling, and operations of application containers across clusters of hosts.
Kubernetes is the leading role in CNCF (Cloud Native Computing Foundation) which will create and drive the evolution of technologies that are container packaged, dynamically scheduled and microservices oriented.

** the use cases of kubernetes
*** targets
    Kubernetes is primarily targeted at applications composed of multiple containers, such as elastic, distributed micro-services. It is also designed to facilitate migration of non-containerized application stacks to Kubernetes. It therefore includes abstractions for grouping containers in both loosely coupled and tightly coupled formations, and provides ways for containers to find and communicate with each other in relatively familiar ways.
*** benefits
With Kubernetes, you are able to quickly and efficiently respond to customer demand:
Scale your applications on the fly.
Seamlessly roll out new features.
Optimize use of your hardware by using only the resources you need.
** main advantages:
lean: lightweight, simple, accessible
portable: public, private, hybrid, multi-cloud
extensible: modular, pluggable, hookable, composable
self-healing: auto-placement, auto-restart, auto-replication
** Design Overview
Kubernetes aspires to be an extensible, pluggable, building-block OSS platform and toolkit. Therefore, architecturally, we want Kubernetes to be built as a collection of pluggable components and layers, with the ability to use alternative schedulers, controllers, storage systems, and distribution mechanisms, and we're evolving its current code in that direction.

* Introduction of Docklet
** Motivation
*** why we should use containers?
*** docklet supports both containers and big data analytics in one data center, achieves higher resource utilization at the same time.
** the use cases of Docklet
*** target
private data center of one coorperation
*** benefits
docklet supports nearly every kinds of workload, it is especially designed for paas offerings, and big data analytics.
** main advantages
*** open source
*** lean
*** portable
*** extensible
** how is Docklet different from DCOS?
*** open source
*** lightweight
** how is Docklet different from Kubernetes?
