* the scalability of the linux block layer
The scalability of the Linux block layer is not an issue that we might encounter in the future, it is a significant problem being faced by HPC in practice today
* RAMCloud
As an extreme point in the design space, RAMCloud9 explored the possibility of keeping all of a cluster's data in DRAM and making it durable via fast recovery mechanisms.
* Storage Class Memories (SCM)
** The arrival of high-speed, non-volatile storage devices, typically referred to as Storage Class Memories (SCM), is likely the most significant architectural change that datacenter and software designers will face in the foreseeable future.
** SCMs are increasingly part of server systems, and they constitute a massive change: the cost of an SCM, at $3-5k, easily exceeds that of a many-core CPU ($1-2k), and the performance of an SCM (hundreds of thousands of I/O operations per second) is such that one or more entire many-core CPUs are required to saturate it.
* some of the techniques and considerations in designing for extremely high performance and utilization in enterprise storage systems
** Balanced System
*** sufficient CPU cores must be available and the network must provide enough connectivity for data to be served out of storage at full capacity
*** Failing to build balanced systems wastes capital investment in expensive SCMs
** Contention-Free I/O-centric scheduling
*** Contention-Free I/O-centric Scheduling is required for multiple CPUs to efficiently dispatch I/O to the same storage device, that is, to share a single SCM without serializing accesses across all the CPUs
** Horizontal Scaling and Placement Awareness
*** High-speed, low-capacity storage is used to cache hot data from the lower-speed tiers, with the system actively promoting and demoting data as workloads change
*** Failing to implement workload-aware tiering results in high-value SCM capacity being wasted on cold data.
** Workload-aware Storage Tiering
